### PR TITLE
Bookstore: styling

### PR DESCRIPTION
**Pull request by TadesseDev**
# Change introduces 😎
---
- Design the  Bookstore app based on the design in [Zeplin](https://zeplin.io/).
- Update AddNewBook component.
- Deploy the app on [netlify](https://app.netlify.com/).
- [Live preview is here](https://tadesse-bookstore.netlify.app/)

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @Tadesse-Alemayehu 

Good job so far! I know you have worked hard on making this milestone. There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there

## Required Changes :recycle:
- [ ] Kindly, make sure that the remove button is working as expected. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
### Dear @Emmyn5600, I checked the review and re-evaluate my remove button. it seems working fine. Please can you review it again?

**Comment by mke2111** [comment]
Project Under Second Opinion Review.
Kindly wait for a response. 😄

**Review by mke2111 — COMMENTED** [review]
Hello @Tadesse-Alemayehu  👋,

_This is an additional review as a result of the second opinion request._

Great work with this project. 👍🏽 

The remove button on the right actually works as you claim. This functionality should have been placed in the `remove` button on the left. I believe this is what the CR checked. But good that the functionality was working just fine.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

**Comment by TadesseDev** [comment]
### @mke2111 Thank you, Now I know what is missing I'll be more than happy to incorporate the changes. Thank you again for the second opinion.

**Comment by TadesseDev** [comment]
### Dear @mke2111, Even though my project has the green light to pass, just to make sure I did all its been requested, I have added the "remove" link functionality. in https://github.com/Tadesse-Alemayehu/Bookstore/pull/5/commits/806943947bc06e41b8a82556dee5f3c879505596 commit hash Feel free to drop me any comment in general that would help me improve into a better me.  🙏🏼

**Review by prolajumokeoni — APPROVED** [review]
Hi @Tadesse-Alemayehu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TadesseDev** [comment]
### Thank you @prolajumokeoni 🙏🏼, Happy coding 😎

**Comment by mke2111** [comment]
All is still perfect @Tadesse-Alemayehu 👍🏽

**Comment by TadesseDev** [comment]
Thank you @mke2111 🙏🏼.

**Pull request merged**
